### ISSUE TITLE
many antd 2.0.1 *.d.ts files couldn't pass the compiling of tsc

### ISSUE THREAD

**Issue by AlbertZheng** [ant-design/ant-design#3358]
#### 发生问题的环境是：
- antd 版本: 2.0.1
- 操作系统及其版本: CentOS 6
- 浏览器及其版本: Chrome 版本 52.0.2743.116 m
- 编译器：TypeScript 1.8.10和2.0.3

#### 您做了什么？
将项目从antd 1.11.1升级到antd 2.0.1

#### 您期待的结果是：
能通过tsc编译。

#### 实际上的结果是：
不少antd components的d.ts文件不能通过tsc编译。编译错误说明如下：

##### A workaround for TS7006 is to manually add any or any[] type declaration for those parameter in the reported d.ts files. But this error "TS2307: Cannot find module 'rc-select'" perhaps will need to write a index.d.ts for rc-select component.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/upload/interface.d.ts
(30,23): error TS7006: Parameter 'File' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/select/index.d.ts
(2,34): error TS2307: Cannot find module 'rc-select'.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/select/index.d.ts
(38,17): error TS7006: Parameter 'value' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/icon/index.d.ts
(5,16): error TS7006: Parameter 'e' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/form/Form.d.ts
(48,30): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/date-picker/index.d.ts
(11,29): error TS7006: Parameter 'trigger' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,19): error TS7006: Parameter 'route' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,26): error TS7006: Parameter 'params' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,34): error TS7006: Parameter 'routes' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,42): error TS7006: Parameter 'paths' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/back-top/index.d.ts
(4,16): error TS7006: Parameter 'event' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/alert/index.d.ts
(16,16): error TS7006: Parameter 'event' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/auto-complete/index.d.ts
(24,17): error TS7006: Parameter 'value' implicitly has an 'any' type.

#### BTW, the four apis are missing in the d.ts file of notification component of antd 2.0.1 when migrated from antd 1.11.x to 2.0.1:

notification.success(config)
notification.error(config)
notification.info(config)
notification.warn(config)

#### 可重现的在线演示
无.

**Comment by AlbertZheng** [comment]
PS: the "disabled" property is also missed in SwitchProps in switch/index.d.ts.

**Comment by afc163** [comment]
Could u help us improve these issues, cause we are short of hands right now. 🤓

**Comment by AlbertZheng** [comment]
@afc163 No problem. I am writing a new app demo using typescript 2.0 and antd 2.0, when it is done I will return my patch files to the community for review.

**Comment by afc163** [comment]
Thx! @AlbertZheng 

ref #3170
