### ISSUE TITLE
Form.onSubmit type error with Formik after updating to v3.19.7

### ISSUE THREAD

**Issue by alex-albericio** [ant-design/ant-design#17400]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/vigilant-breeze-v97uh)

### Steps to reproduce
After upgrading to v3.19.7 we cannot use the "handleSubmit" function of Formik in the onSubmit prop of the Form component. This code no longer compiles: 
```typescript
<Form onSubmit={handleSubmit}/>
```

The type definition for Form.onSubmit was until v3.19.6:
```typescript
onSubmit?: React.FormEventHandler<any>;
```
Beginning with v3.19.7 it has changed to:
```typescript
onSubmit?: React.FormEventHandler<HTMLElement>;
```

Shouldn't the generic type variable be **HTMLFormElement instead of HTMLElement** since these are all form elements events?

### What is expected?
No compilation error

### What is actually happening?
(JSX attribute) onSubmit?: ((event: React.FormEvent<HTMLElement>) => void) | undefined
Type '(e?: FormEvent<HTMLFormElement> | undefined) => void' is not assignable to type '(event: FormEvent<HTMLElement>) => void'.
  Types of parameters 'e' and 'event' are incompatible.
    Type 'FormEvent<HTMLElement>' is not assignable to type 'FormEvent<HTMLFormElement>'.
      Type 'HTMLElement' is missing the following properties from type 'HTMLFormElement': acceptCharset, action, autocomplete, elements, and 12 more.ts(2322

| Environment | Info |
|---|---|
| antd | 3.19.7 |
| React | 16.8.6 |
| System | OSX |
| Browser | Chrome |

**Comment by alex-albericio** [comment]
CodeSandbox actually lets you run the code of the reproduction example, somehow ignoring the error. But, in IntelliJ IDEA, the error cannot be ignored.

**Comment by afc163** [comment]
Fixed in 3.19.8

https://ant.design/changelog#3.19.8

**Comment by alex-albericio** [comment]
Excuse me, but I'm seeing the same type currently on [master](https://github.com/ant-design/ant-design/blob/master/components/form/Form.tsx):
````onSubmit?: React.FormEventHandler<HTMLElement>````

The generic type variable was changed from "any" to "HTMLElement" in [#14044](https://github.com/ant-design/ant-design/commit/f1ee189bd2b187b8a91d158067ac5db7dd9c9ea4#diff-2387fe20e406362ba8d6c4745181f2d0) and I think it wasn't reverted in [#17249](https://github.com/ant-design/ant-design/commit/4c84c41da0074f86a0491c3cc68e54995609220e#diff-2387fe20e406362ba8d6c4745181f2d0).

**Comment by afc163** [comment]
Could you give us a reproduce demo?

**Comment by alex-albericio** [comment]
There's a CodeSandbox reproduction link on top of this ticket. You should see an error hint like this:

<img width="270" alt="Captura de pantalla 2019-07-02 a las 12 42 21" src="https://user-images.githubusercontent.com/9462221/60506774-e6bb4100-9cc6-11e9-8f79-1bab8c030001.png">

**Comment by alex-albericio** [comment]
Cool! Thanks for the fix @afc163 👍
