### ISSUE TITLE
Typescript: expose Tooltip align interface

### ISSUE THREAD

**Issue by magnnus** [ant-design/ant-design#12321]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### What problem does this feature solve?
When I update my antd version to 3.9.2 (before: 2.13.4) and begin to use Typescript in my app, I find that the 'popupAlign' prop can't be used any more. Then I check the rc-tooltip package, and use a new prop called 'align' , But I get a error tip:  TS2339: Property 'align' does not exist on type 'IntrinsicAttributes & IntrinsicClassAttributes<Tooltip>  .... .  At last  I check the Tooltip component source code in antd, there is no 'align' interface. Could you expose the interface?

### What does the proposed API look like?
interface ITooltipAlignConfig {
  points?: [string, string],
  offset?: [number, number],
  targetOffset?: [number, number],
  overflow?: { adjustX: boolean, adjustY: boolean },
  useCssRight?: boolean,
  useCssBottom?: boolean,
  useCssTransform?: boolean
}

export interface AbstractTooltipProps {  
  align?: ITooltipAlignConfig 
  ...
}

**Comment by zombieJ** [comment]
Wow. Such detail. 
Do you have interesting to create a PR for this? 😄

**Comment by magnnus** [comment]
@zombieJ Yes, I am so glad to create a PR, but I wonder if I need to write test cases. Because the 'align' prop is need by the rc-tooltip component.

**Comment by zombieJ** [comment]
Add typescript def don't need the test case : )
