### ISSUE TITLE
typescript compiler error in 3.24.1 - regression

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#19276]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://asdfasdf](http://asdfasdf)

### Steps to reproduce
compile with typescript 3.6.4

### What is expected?
compile without error

### What is actually happening?
lots of errors like this. reverting to antd 3.23.6 compiles successfully, thus its a regression.

```
node_modules/rc-menu/lib/Divider.d.ts:1:8 - error TS1259: Module '"D:/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaul
tImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:55:1
    55 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

node_modules/rc-menu/lib/Menu.d.ts:1:8 - error TS1259: Module '"D:/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultIm
ports' flag

1 import React from 'react';
         ~~~~~

```

| Environment | Info |
|---|---|
| antd | 3.24.1 |
| React | 16.10.2 |
| System | windows |
| Browser | chrome latest |

**Comment by shaodahong** [comment]
should be using `import * as React from 'react';`

**Comment by shaodahong** [comment]
@pdeva do you resolve it? if not, maybe you can reproduce an example

**Comment by pdeva** [comment]
@shaodahong the import error is coming from inside antd, not mt code.
its antd that needs to fix its import

**Comment by pdeva** [comment]
the import in this line is causing the errors
https://github.com/react-component/menu/blob/master/src/Divider.tsx

**Comment by shaodahong** [comment]
@pdeva yep, `rc-menu` use typescript option `allowSyntheticDefaultImports`, can you add `"allowSyntheticDefaultImports": true` option in your `tsconfig.json` > `compilerOptions`

**Comment by shaodahong** [comment]
@afc163 @zombieJ  In my see, Umi `father compile` default `tsconfig.json` enable `allowSyntheticDefaultImports`, so I don't know we need to keep `import * as React from 'react';` in the all  `rc-component`

**Comment by afc163** [comment]
https://ant.design/changelog#Other-things

<img width="907" alt="图片" src="https://user-images.githubusercontent.com/507615/67139180-bf8d7d00-f27f-11e9-882e-a32cc4b90440.png">

We should turn off `allowSyntheticDefaultImports` of `father compile`.

**Comment by shaodahong** [comment]
Closed via https://github.com/react-component/menu/commit/907b4f790d68f398f381243bb27ad87161cc2745
