### ISSUE TITLE
Compilation error after upgrading to 3.11

### ISSUE THREAD

**Issue by tommycarpi** [ant-design/ant-design#14103]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Steps to reproduce
yarn start

### What is expected?
no compilation error

### What is actually happening?
Compilation error: .
/node_modules/rc-drawer/es/Drawer.js
372:16-29 './utils' does not contain an export named 'transitionStr'.

| Environment | Info |
|---|---|
| antd | 3.11.6 |
| React | 16.7.0 |
| System | MacOS 10.14.2 |
| Browser | Chrome |

**Comment by afc163** [comment]
https://github.com/react-component/drawer/issues/61

**Comment by ztplz** [comment]
@tommycarpi  It's work fine When I compile locally. Could you provide a `mini git repo` for me to reproduce this problem ?

**Comment by jljsj33** [comment]
`rm -rf node_modules package-lock.json && npm install`

https://github.com/react-component/drawer/issues/58
