### ISSUE TITLE
Select filterOption option parameter has a type definition of array instread of string (Property 'toLowerCase' does not exist on type 'Omit<DefaultOptionType, "children">[]')

### ISSUE THREAD

**Issue by gitter-me** [ant-design/ant-design#33643]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/react-context-example-for-ts-forked-98uo2?file=/src/index.tsx)

### Steps to reproduce
1. Use the example out of the documentation for select ( https://ant.design/components/select/#When-To-Use => Select with search field)
2. Change it to typescript

### What is expected?
The example uses children as a  string, it calls the string function toLowerCase on it (option.children.toLowerCase().indexOf(input.toLowerCase()) >= 0)
But the type on it is more or less a array type: Omit<DefaultOptionType, "children">[] 

### What is actually happening?
If you console.log the children value, its  a string, a object with $$typeof: Symbol(react.element) or undefined.

| Environment | Info |
|---|---|
| antd | 4.18.2 |
| React | - |
| System | - |
| Browser | - |

---
I assume the type is not correct anymore.
It was working in antd 4.17.4

**Comment by zombieJ** [comment]
4.17.x marks `children` as any which is not correct definition: https://codesandbox.io/s/react-context-example-for-ts-forked-0gwtz?file=/src/index.tsx

For 4.18.x, we support Generic of OptionType to enhance type check. You can do as follow: https://codesandbox.io/s/react-context-example-for-ts-forked-tv8i1?file=/src/index.tsx:151-157

**Comment by dinosaadeh** [comment]
> neric of Opti

Thanks for your solution. I'm kind of a noob in Typescript but if I don't want to specify onSearch and onChange your solution gives me the following typescript error.. Any guidance will be appreciated


```
Type '{ children: Element[]; id: string; labelInValue: true; showSearch: true; className: string; optionFilterProp: string; filterOption: (input: string, option: { value: string; children: string; } | undefined) => boolean; ... 10 more ...; disabled?: boolean | undefined; }' is not assignable to type 'SelectProps<string | number, { value: string; children: string; }>'.
  Types of property 'onChange' are incompatible.
    Type 'ChangeHandler' is not assignable to type '(value: string | number, option: { value: string; children: string; } | { value: string; children: string; }[]) => void'.
      Types of parameters 'event' and 'value' are incompatible.
        Type 'string | number' is not assignable to type '{ target: any; type?: any; }'.
          Type 'string' is not assignable to type '{ target: any; type?: any; }'.ts(2322)
```
