### ISSUE TITLE
compile fail after update 3.6.2 to 3.14.1

### ISSUE THREAD

**Issue by lbottoni** [ant-design/ant-design#15290]
- [ ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[http://localhost](http://localhost)

### Steps to reproduce
update version 3.6.2 to 3.14.1

### What is expected?
success ts compilation

### What is actually happening?
# npm run compile

> @private/react-lib-src@0.9.2 compile C:\xampp\htdocs\react-component-library\packages\lib-src
> npm-run-all -s compile:tsc compile:less copyfiles

> @private/react-lib-src@0.9.2 compile:tsc C:\xampp\htdocs\react-component-library\packages\lib-src
> tsc --pretty

node_modules/antd/lib/_util/type.d.ts:2:50 - error TS2370: A rest parameter must be of an array type.

2 export declare const tuple: <T extends string[]>(...args: T) => T;
                                                   ~~~~~~~~~~


node_modules/antd/lib/_util/type.d.ts:3:53 - error TS2370: A rest parameter must be of an array type.

3 export declare const tupleNum: <T extends number[]>(...args: T) => T;
                                                      ~~~~~~~~~~

node_modules/antd/lib/layout/Sider.d.ts:59:30 - error TS2304: Cannot find name 'MediaQueryListEvent'.

59     responsiveHandler: (mql: MediaQueryListEvent | MediaQueryList) => void;
                                ~~~~~~~~~~~~~~~~~~~


node_modules/antd/lib/locale-provider/index.d.ts:50:48 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

50     render(): string | number | boolean | {} | React.ReactElement<any, string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)> | React.ReactPortal | null | undefined;
                                                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

node_modules/antd/lib/tree/Tree.d.ts:157:59 - error TS2314: Generic type 'ReactElement<P>' requires 1 type argument(s).

157     renderSwitcherIcon: (prefixCls: string, switcherIcon: React.ReactElement<any, string | ((props: any) => React.ReactElement<any, string | any | (new (props: any) => React.Component<any, any, any>)> | null) | (new (props: any) => React.Component<any, any, any>)> | undefined, { isLeaf, expanded, loading }: AntTreeNodeProps) => JSX.Element | null;
                                                              ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~


src/form/MaterializedSelect.tsx:23:9 - error TS2554: Expected 1 arguments, but got 0.

23         this.props.onBlur();
           ~~~~~~~~~~~~~~~~~~~

| Environment | Info |
|---|---|
| antd | 3.14.1 |
| React | ^16.5.0 |
| System | window 10 |
| Browser | any |

---
ts compile with "typescript": "3.1.3"


<!-- generated by ant-design-issue-helper. DO NOT REMOVE -->

**Comment by afc163** [comment]
Please upgrade TypeScript and `@types/react` to latest version.

**Comment by lbottoni** [comment]
i have the last @type\react and now i have this error

> tsc --pretty

node_modules/antd/lib/_util/type.d.ts:2:50 - error TS2370: A rest parameter must be of an array type.

2 export declare const tuple: <T extends string[]>(...args: T) => T;
                                                   ~~~~~~~~~~


node_modules/antd/lib/_util/type.d.ts:3:53 - error TS2370: A rest parameter must be of an array type.

3 export declare const tupleNum: <T extends number[]>(...args: T) => T;
                                                      ~~~~~~~~~~


node_modules/antd/lib/layout/Sider.d.ts:59:30 - error TS2304: Cannot find name 'MediaQueryListEvent'.

59     responsiveHandler: (mql: MediaQueryListEvent | MediaQueryList) => void;


package.json
`
 "devDependencies": {
    "@types/jest": "^23.3.2",
    "@types/react": "^16.8.7",
    "@types/react-dom": "^16.0.7",
    "@types/react-test-renderer": "^16.0.2",
    "@webpack-blocks/assets": "^1.0.0",
    "@webpack-blocks/postcss": "^1.0.0",
    "@webpack-blocks/typescript": "^1.0.0",
    "copyfiles": "^1.2.0",
    "html-entities": "^1.2.0",
    "identity-obj-proxy": "^3.0.0",
    "jest": "^23.6.0",
    "less": "^2.7.3",
    "npm-run-all": "^4.1.2",
    "react": "^16.5.0",
    "react-docgen": "^2.20.1",
    "react-docgen-typescript": "^1.8.1",
    "react-dom": "^16.5.0",
    "react-styleguidist": "^7.3.7",
    "react-test-renderer": "^16.5.0",
    "ts-jest": "^23.1.4",
    "webpack": "^3.10.0",
    "webpack-blocks": "^1.0.0-rc.2",
    "webpack-blocks-less": "^0.2.0"
  },
  "dependencies": {
    "@types/backbone": "^1.3.43",
    "@types/jquery": "^3.3.5",
    "@types/material-ui": "^0.21.5",
    "@types/webpack-env": "^1.13.6",
    "antd": "3.14.1",
    "backbone": "^1.3.3",
    "bootstrap": "^3.3.7",
    "bootstrap-switch": "^3.3.4",
    "cron-parser": "^2.4.1",
    "extended-proptypes": "^1.3.0",
    "font-awesome": "^4.7.0",
    "highcharts": "^4.2.7",
    "jquery": "^3.2.1",
    "jquery-ui-dist": "^1.12.1",
    "lodash": "^4.17.4",
    "material-ui": "0.20.0",
    "moment": "^2.20.1",
    "open-sans-fontface": "^1.4.0",
    "platform": "^1.3.5",
    "prop-types": "^15.6.0",
    "react-addons-css-transition-group": "^15.4.2",
    "react-autobind": "^1.0.6",
    "react-flag-kit": "0.2.3",
    "react-md-spinner": "^0.2.2",
    "simple-line-icons": "^2.4.1",
    "underscore": "^1.8.3",
    "utility-types": "^2.0.0"
  },
`

**Comment by ztplz** [comment]
@lbottoni  Could you provide a `mini git repo` for your issue ? It's so hard to figure out the problem without reproduce.

**Comment by lbottoni** [comment]
@ztplz i try, i know it's complicated. Now i try to create the repo..

**Comment by ztplz** [comment]
@lbottoni  Thanks for your understanding, good luck.

**Comment by lbottoni** [comment]
@ztplz FYI, if i install antd 3.9.4 (last of 3.9.*) i not have any problem. If i install the 3.10.0 it appears the first problem

> node_modules/antd/lib/layout/Sider.d.ts:58:30 - error TS2304: Cannot find name >'MediaQueryListEvent'.
>
>58     responsiveHandler: (mql: MediaQueryListEvent | MediaQueryList) => void;

always with last @type/react. I have searched in change log of antd, but nothing about **MediaQueryList*  :*(

https://ant.design/changelog#3.10.0

**Comment by ztplz** [comment]
What's the version of typescript in your project ?

**Comment by lbottoni** [comment]
we use lerna for separate our projects and in the root i have setted ^3.1.3 and is it installed the 3.3.3

**Comment by lbottoni** [comment]
@ztplz resolved, was wrong version of tsc installed globally. it was 2.9.2, after call the cmd

` npm install -g typescript@latest `

### now i have 

`tsc --version`
`Version 3.3.3333`

**Comment by afc163** [comment]
<img width="521" alt="图片" src="https://user-images.githubusercontent.com/507615/54125958-620b9500-4441-11e9-82fb-4ba0b4ce95ed.png">

And you ignore my suggestion and give me a 👎 ...

**Comment by lbottoni** [comment]
do it!!!!NOT WORK!!!!!

**Comment by ThienMD** [comment]
not working
