### ISSUE TITLE
rewrite in typescript

### ISSUE THREAD

**Issue by yiminghe** [ant-design/ant-design#1846]
@all

https://www.typescriptlang.org/docs/handbook/basic-types.html

demo: https://github.com/ant-design/ant-design/blob/master/components/affix/index.tsx
recommended IDE: visual studio code / idea

### env

```
npm i typings -g
typings install
```

### change react import
```js
import React from 'react';
import ReactDOM from 'react-dom';
```
to

```js
import * as React from 'react';
import * as ReactDOM from 'react-dom';
```
### add reference to components/index.tsx
```js
import Xx from './xx';
export { Xx };
```
### change index.js to
```js
module.export = require('./src/');
console.warn('you are ....')
```
## components

  * --------- @afc163 ---------
  * [x] affix
  * [x] alert
  * [x] badge
  * [x] breadcrumb
  * [x] button
  * [x] card
  * --------- @benjycui ---------
  * [x] calendar
  * --------- @RaoHai  ---------
  * [x] checkbox
  * [x] collapse
 
  * [x] dropdown
  * [x] form
  * --------- @benjycui ---------
  * [x] date-picker
  * [x] icon
  * [x] input
  * [x] input-number
  * [x] layout
  * --------- @ddcat1115 ---------
  * [x] locale-provider
  * [x] menu
  * [x] message
  * [x] modal
  * [x] notification
  * [x] pagination
  * [x] popconfirm
  * [x] popover
  * [x] progress
  * [x] radio
  * --------- @benjycui ---------
  * [x] rate
  * [x] select
  * [x] slider
  * [x] spin
  * [x] steps
  * [x] switch
  * [x] table
  * --------- @bang88 ---------
  * [x] tabs
  * [x] tag
  * [x] time-picker
  * [x] timeline
  * [x] tooltip
  * --------- @GrayChoi ---------
  * [x] transfer
  * [x] tree
  * [x] carousel
  * [x] cascader
  * --------- @afc163 ---------
  * [x] tree-select
  * [x] upload

---

- [x] Make sure no tsc errors (Add tsc into `npm run lint`)
- [x] delete index.d.ts
- [x] change index.js to ...

This will close #973

**Comment by waywardmonkeys** [comment]
Is this going to happen? (I think it would be great!)

**Comment by yiminghe** [comment]
affix ok

**Comment by afc163** [comment]
Add https://github.com/buzinas/tslint-eslint-rules for missing eslint rules like [object-curly-spacing](http://eslint.org/docs/rules/object-curly-spacing)

**Comment by bang88** [comment]
Maybe i can do something about this topic. but don't know your plan yet.

**Comment by yiminghe** [comment]
@bang88 move types in index.d.ts to components , see affix, welcome pr

**Comment by afc163** [comment]
Assigned and updated

**Comment by afc163** [comment]
@bang88 Maybe you can help us to rewrite some components which is assigned to you above.

**Comment by afc163** [comment]
@waywardmonkeys Maybe you can help us to rewrite some components which is assigned to you above. (If you want to 🎅 )

**Comment by bang88** [comment]
@afc163 OK.can we have a develop instruction? how to rewrite it using ts,and how to test it.
By the way, `npm start` failed on `windows`.

**Comment by afc163** [comment]
Develop instruction: https://github.com/ant-design/ant-design/wiki/Development#local-development

We don't support develop in windows now. :sad: You can help us improve that too.

**Comment by bang88** [comment]
@afc163 @yiminghe 

I add some typings for `Tabs`.but not sure this is ok ?.can you have a look... Thanks
https://github.com/bang88/ant-design/commit/72965da807516c69c65a3a53379c96cc661aab27

**Comment by RaoHai** [comment]
https://github.com/ant-design/ant-design/pull/2167/commits/3c4dec27dbbab1988b273bfa13b0aa645b46a147

是这样改的么？总感觉哪里不对的样子

**Comment by yiminghe** [comment]
after modification, use vs code to open project and check

**Comment by GrayChoi** [comment]
我也可以帮忙用typescript重写一部分组件，如果需要的话。

**Comment by dyf2015** [comment]
??ts?????????

???? iPhone

? 2016?6?26??13:07?Gray Choi <notifications@github.com<mailto:notifications@github.com>> ???


???????typescript???????????????

-

**Comment by maolion** [comment]
赞!

**Comment by maolion** [comment]
我也可以帮忙，如果有需要的话。

**Comment by afc163** [comment]
@GrayChoi @maolion updated and thx

**Comment by maolion** [comment]
@afc163 看到了，最近很少关注antd的动态。

**Comment by infeng** [comment]
i use typescript a long time, i can help

**Comment by xuyang2** [comment]
我也可以帮忙用 TypeScript 重写一部分组件，如果需要的话。

**Comment by benjycui** [comment]
看来大家都是对写代码感兴趣，不喜欢写文档 😂

**Comment by yeliex** [comment]
@benjycui 我可以帮忙更新文档 如果需要的话

**Comment by benjycui** [comment]
@yeliex THX, and see: https://github.com/ant-design/ant-design/issues/1471

**Comment by afc163** [comment]
ce7e7c77f04426b207b388c67c3eca311840e896

这里的一些修改点备忘：

1. `ReactDOM.findDOMNode(this)` 需要写成 `ReactDOM.findDOMNode(this) as HTMLElement;`。避免读取相关 dom 属性报错。
2. 使用到的 this.xxx 在 class 里定义。
   
   ```diff
     export default class Affix extends React.Component<AffixProps, any> {
   +  scrollEvent: any;
   +  resizeEvent: any;
   +  refs: {
   +    fixedNode: any;
   +  }
   ```

**Comment by benjycui** [comment]
当自己负责的组件已经重写并被合并后，在顶楼打个勾？不然完全不知道进度。。

**Comment by bang88** [comment]
No permissions 😄

**Comment by hotoo** [comment]
Without static types, I can't find any useful different between the ES2015 and TypeScript.

**Comment by waywardmonkeys** [comment]
@hotoo Part of that is because we already went through and converted a lot of the JavaScript to use the more modern features and make it more like TypeScript. But having automatically maintained typings for consumers who are using TypeScript is very useful.

**Comment by wenxiongid** [comment]
现在还差rewrite typescript的人吗？我看repo里的component都重写好了

**Comment by afc163** [comment]
You can help me rewrite these components: @wenxiongid 

 * [ ] button
 * [ ] calendar
 * [ ] card

**Comment by wenxiongid** [comment]
ok，我先申请个calendar

**Comment by afc163** [comment]
@maolion any progress about tree-select and upload?

**Comment by afc163** [comment]
context 的照这个来：https://github.com/ant-design/ant-design/commit/7a52a6fafe1fbe0629df055013139a2551208a07

**Comment by benjycui** [comment]
@wenxiongid if you have no time, I am going to finish your tasks, OK?

**Comment by wenxiongid** [comment]
@benjycui OK, sorry for my busy job these days

**Comment by plandem** [comment]
omg...looks like it's going to happen :)

**Comment by benjycui** [comment]
Jobs done ! @afc163 @benjycui @RaoHai @ddcat1115 @bang88 @GrayChoi

But, there still leave a lot to be improved. 😄

**Comment by afc163** [comment]
- [ ] Make sure no tsc errors
- [ ] delete index.d.ts
- [ ] change index.js to ...

No finshed.

**Comment by benjycui** [comment]
> Make sure no tsc errors (Add tsc into npm run lint)

WIP

**Comment by benjycui** [comment]
> change index.js to ...

@afc163 ??

**Comment by afc163** [comment]
Look at https://github.com/ant-design/ant-design/issues/1846#issue-156699638

**Comment by ziaochina** [comment]
很想知道为啥要换TypeScript呢?

**Comment by afc163** [comment]
@ziaochina https://github.com/ant-design/ant-design/issues/973

**Comment by ziaochina** [comment]
@afc163 除了#973,有微软方面的原因吗?

**Comment by AlbertZheng** [comment]
When migrated from antd 1.11.x to 2.0.1, there are many errors reported by tsc 1.8.10 and 2.0.3 as the following. Please have a check:

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/upload/interface.d.ts
(30,23): error TS7006: Parameter 'File' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/select/index.d.ts
(2,34): error TS2307: Cannot find module 'rc-select'.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/select/index.d.ts
(38,17): error TS7006: Parameter 'value' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/icon/index.d.ts
(5,16): error TS7006: Parameter 'e' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/form/Form.d.ts
(48,30): error TS7019: Rest parameter 'args' implicitly has an 'any[]' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/date-picker/index.d.ts
(11,29): error TS7006: Parameter 'trigger' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,19): error TS7006: Parameter 'route' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,26): error TS7006: Parameter 'params' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,34): error TS7006: Parameter 'routes' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
(7,42): error TS7006: Parameter 'paths' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/back-top/index.d.ts
(4,16): error TS7006: Parameter 'event' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/alert/index.d.ts
(16,16): error TS7006: Parameter 'event' implicitly has an 'any' type.

ERROR in /home/vagrant/apps/r0/node_modules/antd/lib/auto-complete/index.d.ts
(24,17): error TS7006: Parameter 'value' implicitly has an 'any' type.

**Comment by AlbertZheng** [comment]
BTW, the four apis are missing in the d.ts file of notification component of antd 2.0.1 when migrated from antd 1.11.x to 2.0.1:

notification.success(config)
notification.error(config)
notification.info(config)
notification.warn(config)
