### ISSUE TITLE
message.warn(content, [duration], onClose) does not exist as referred in documentation

### ISSUE THREAD

**Issue by mehdirazak** [ant-design/ant-design#39086]
### Reproduction link

[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/antd-reproduction-template-forked-jyh2k9?file=/index.js)

### Steps to reproduce

import "message" from antd and call "warn" method on it with content-text and display-duration information.

### What is expected?

The message should be displayed on screen with specified text for the specified duration (similar to message.warning) 

### What is actually happening?

TypeError: _antd.message.warn is not a function

| Environment | Info |
| --- | --- |
| antd | 5.0.2 |
| React | 4.7.1 |
| System | Windows 11 10.0.22000 Build 22000 |
| Browser | Chrome 107.0.5304.107 |

---
The documentation states message.warn to be an alias for message.warning but this is not the case. I ran into this bug after upgrading antd from V4 to V5

**Comment by MadCcc** [comment]
`message.warn` is removed in V5. Please use `message.warning` instead.

**Comment by any1024** [comment]
我来改这个文档吧

**Comment by any1024** [comment]
文档中显示还支持，需要修改了吗
<img width="612" alt="image" src="https://user-images.githubusercontent.com/32009993/204499552-b1f74901-d3c0-4460-ae21-6ecc4c2d3aab.png">

**Comment by afc163** [comment]
@any1024 changelog 和升级文档里也要加上相关提示

**Comment by any1024** [comment]
> @any1024 changelog 和升级文档里也要加上相关提示

好的，我加一下
