### ISSUE TITLE
Typescript Compilation issue; 

### ISSUE THREAD

**Issue by jjones-imodules** [ant-design/ant-design#10579]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.5.2

### Environment
```
react@^16.2.0
react-dom@^16.2.0
typescript@^2.8.1
@types/react@^16.0.35
@types/react-dom@^16.0.3
```

### Reproduction link
This is a compilation issue.

### Steps to reproduce
run `yarn build`

### What is expected?
no compilation error

### What is actually happening?
```
Failed to compile.

C:/git/email-home/node_modules/antd/lib/badge/ScrollNumber.d.ts
(48,43): Generic type 'Component<P, S>' requires between 0 and 2 type arguments.
```

---
Probably introduced in #9931. Any version greater than v3.4.0 has this issue.

I have temporarily added `"skipLibCheck": true` to `tsconfig.json`. This cannot be a long-term solution though.
