### ISSUE TITLE
Incorrect typescript interface for RcFile in Upload component [regression]

### ISSUE THREAD

**Issue by apieceofbart** [ant-design/ant-design#11625]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.8.0

### Environment
all

### Reproduction link
[http://check.the.description](http://check.the.description)

### Steps to reproduce
Try to build using Typescript and antd version 3.8.0

### What is expected?
Build is ok

### What is actually happening?
Build fails with:
```
node_modules/antd/lib/upload/interface.d.ts:6:18 - error TS2430: Interface 'RcFile' incorrectly extends interface 'File'.
  Property 'lastModifiedDate' is optional in type 'RcFile' but required in type 'File'.
```
---
This was introduced here (`lastModifiedDate` is optional):
https://github.com/ant-design/ant-design/commit/2f81349c21d6acaf529a1c8dff77fba1f2fb7139#diff-eeab2da14d4b4db1d3de81fa26173037R11

It is in conflict with the typescript lb typings (`lastModifiedDate` is required):
https://github.com/Microsoft/TypeScript/blob/master/lib/lib.dom.d.ts#L5282

Can we revert that change? (I can create a PR)

**Comment by apieceofbart** [comment]
Sorry, I think my `lb` typings are not update

**Comment by 104gogo** [comment]
@apieceofbart Old iron, could you tell me use typescript@3.0.0 is right?

**Comment by apieceofbart** [comment]
@104gogo yes, I think that is the case

**Comment by sbusch** [comment]
Typescript 3.0 doesn't work for now due to some errors related to defaultProps interpretation, see https://github.com/ant-design/ant-design/issues/11677

**Comment by sbusch** [comment]
Fixed for TypeScript 2.9.2 users in [latest antd release `3.8.1`](https://ant.design/changelog#3.8.1)
