### ISSUE TITLE
import the antd theme, webpack build show .bezierEasingMixin error ?

### ISSUE THREAD

**Issue by huyansheng3** [ant-design/ant-design#7927]
### Version
2.13.6

### Environment
npm 7,  "antd": "^2.13.6",

### Reproduction link
[http://github.com](http://github.com)

### Steps to reproduce
1.create react app eject，
2. then set the less-loader,
3.@import "~antd/dist/antd.less";
4. build ,then show the error 
https://ant.design/docs/react/customize-theme-cn#1)-package.theme%EF%BC%88%E6%8E%A8%E8%8D%90%EF%BC%89

### What is expected?
build success!

### What is actually happening?
Module build failed:

// https://github.com/ant-design/ant-motion/issues/44
.bezierEasingMixin();
^
Inline JavaScript is not enabled. Is it set in your options?
      in /Users/MacBook/Documents/2017/react-admin-template/node_modules/antd/lib/style/color/bezierEasing.less (line 108, column 0)

---
看起来是 那行less的写法 less-loader 不认，就报错了。
![image](https://user-images.githubusercontent.com/11534583/31714259-fef1d1a8-b3c5-11e7-8a35-a36731ddc4b0.png)

**Comment by huyansheng3** [comment]
![image](https://user-images.githubusercontent.com/11534583/31715423-6d07232a-b3c9-11e7-97d2-c1655cbb673e.png)

this less new version bug!!!!! close!

**Comment by afc163** [comment]
```
 Inline JavaScript is not enabled. Is it set in your options?
```

You can try turn on the inline javascript option.

**Comment by billgo** [comment]
where to set this opiion ?

**Comment by Lovesueee** [comment]
> version: antd@2.x

less@2.x 是OK的。

less@3.x，需要开启 配置项 javascriptEnabled: true

```js
{ loader: 'less-loader', options: { javascriptEnabled: true } }
```

但依然有错误：

![image](https://user-images.githubusercontent.com/1896831/36766654-c5824910-1c71-11e8-9b63-295afa844188.png)

**Comment by yutingzhao1991** [comment]
@Lovesueee track with https://github.com/less/less.js/issues/3113

**Comment by billgo** [comment]
@Lovesueee 降级 less 到 2.7.2 就到了，less 升级到 3.0.0 后出现这个问题。

**Comment by bkniffler** [comment]
Seems like its up to antd to implement less plugins instead of using the function hack. When can we expect a fix @yesmeck?

**Comment by yesmeck** [comment]
Fixed in https://github.com/ant-design/ant-design/commit/9634bea391dd2b7b17f1e89383577e248081a044

**Comment by madisvain** [comment]
@yesmeck not sure why but I still get the exception even with 3.3.0 release. When downgrading to 2.7 everything works as expected.

**Comment by yesmeck** [comment]
@madisvain `{ loader: 'less-loader', options: { javascriptEnabled: true } }`

**Comment by yuleiQ** [comment]
配置好不报错 样式还是不显示是怎么了

**Comment by webMasterMrBin** [comment]
antd  3.6.3
less 2.7.2
less-loader 4.1.0
![image](https://user-images.githubusercontent.com/25171709/41594985-d91a80fe-73f7-11e8-973b-b64b517fdd5d.png)

**Comment by afc163** [comment]
@webMasterMrBin Try not to parse css files via less-loader

**Comment by webMasterMrBin** [comment]
@afc163 多谢 补充了下webpack 基础

**Comment by FeynmanDNA** [comment]
I didn't eject the create-react-app, and I am using `react-app-rewire-less`, and when i update the package from 2.1.1 to 2.1.2, the same issue occurred. 

My solution is keep the version to "2.1.1" in `package.json`. 

Hope it helps.

**Comment by froston** [comment]
@FeynmanDNA  or you can add this option to config-overrides.js:

``` javascript
config = rewireLess.withLoaderOptions({
  javascriptEnabled: true 
})(config, env);
```

**Comment by FeynmanDNA** [comment]
@froston thanks! it works for me

**Comment by ulisescarreonalvarez** [comment]
I added the @froston script on the console i get:

```
Failed to compile
./src/resources/_antd.less
Module build failed: 


.antCheckboxFn();
^
Cannot read property 'eval' of null
      in /Users/ulisescarreon/Sites/doux_repositories/cleanui-admin-template-react/node_modules/antd/lib/checkbox/style/index.less (line 4, column 0)
```

any advice?

**Comment by tarun14691** [comment]
@froston : Grt help. Works well 💯

**Comment by Remimstr** [comment]
Isn't it unsafe to enable inline javascript?

**Comment by hecomp** [comment]
Hey @ulisescarreonalvarez did you get it fixed?

**Comment by ulisescarreonalvarez** [comment]
@hecomp 

Hi just change on package.json this:

`    "react-app-rewire-less": "^2.1.1",`

to this:

`    "react-app-rewire-less": "2.1.1",`

**Comment by hecomp** [comment]
Hi @ulisescarreonalvarez what's your antd version? 
Getting this now.
`./src/resources/_antd.less
Module build failed: Error: Cannot find module 'less'`

Mine is 3.5.3

**Comment by hecomp** [comment]
@ulisescarreonalvarez can you share your config-override.js?

**Comment by matthew-dean** [comment]
@Remimstr 

> Isn't it unsafe to enable inline javascript?

It can be. The danger is that it's sometimes common for Less libraries to have an "online configuration" for variables to enable theming. If you don't sanitize that input, then you're essentially evaluating any code like:

```less
@theme-color: `code_to_delete_my_whole_computer_oops()`
```

So by forcing users to override the javascriptEnabled option to continue using this library, you're essentially opening a potential security hole that disabling it prevents. True, it only happens when you've put unsanitized input into Less with that option, but without the option, the unsanitized input simply wouldn't parse. That's why it's better to fix the design library and use the `@plugin` syntax rather than forcing the `javascriptEnabled: true` option.

**Comment by afc163** [comment]
@matthew-dean Could you help us achieving that?

**Comment by matthew-dean** [comment]
Based on an issue I filed a while ago, it appears that yes, you're leaking globals into the root namespace on purpose.  https://github.com/ant-design/ant-design/issues/11097

But this isn't just bad practice for Less, it's bad practice in JavaScript / NPM development. Why are you wrapping a function in Less in order to leak globals? If this is required in another JS library, why isn't that being imported directly? On its face, it seems to have nothing to do with styles, since I can't tell what these leaked globals are used for.

**Comment by matthew-dean** [comment]
I did a search for code in the whole organization and I couldn't find anyplace that `this.colorEasing` is referenced. So this code is baffling to me. https://github.com/search?q=org%3Aant-design+this.colorEasing&type=Code

**Comment by Remimstr** [comment]
@matthew-dean Thank you for addressing my question!

**Comment by matthew-dean** [comment]
@afc163 Made a PR here. https://github.com/ant-design/ant-design/pull/13242

Hope that helps.

**Comment by Picktarget** [comment]
hey man，I met an error seems like to this,when I use antd .


./src/index.less
Module build failed: 

// https://github.com/ant-design/ant-motion/issues/44
.tinyColorMixin();
^

and my config-overrides.js 
const { injectBabelPlugin } = require('react-app-rewired');
const rewireLess = require('react-app-rewire-less');

module.exports = function override(config, env) {
  config = injectBabelPlugin(
    ['import', { libraryName: 'antd', libraryDirectory: 'es', style: true }], // change importing css to less
    config
  );
  config = rewireLess.withLoaderOptions({
    javascriptEnabled: true
  })(config, env);
  return config;
};

my package.json like this

  "react-app-rewire-less": "^2.1.3",
    "react-app-rewired": "^1.6.2",

**Comment by m1337e** [comment]
Hey - I'm trying to migrate a project from jsx to jsx + ts.
It's actually merging an admin template with something already developed using JHipster.

I'm getting the following error that I see others have had in this thread...

> ERROR in ./src/resources/_antd.less (./node_modules/css-loader??ref--9-1!./node_modules/less-loader/dist/cjs.js??ref--9-2!./src/resources/_antd.less)
Module build failed (from ./node_modules/less-loader/dist/cjs.js):
.antCheckboxFn();
^
Cannot read property 'eval' of null
      in C:\Users\Michael.Mcmeekin\Documents\ws\cleanui-typescript\node_modules\antd\lib\checkbox\style\index.less (line 4, column 0)

and in my webpack config I'm using the less-loader javascript option.
Disabling this shows the 'Inline Javascript' error, and Enabling shows the above.

Any ideas?

webpack.dev.js
  module: {
    rules: [
      {
        test: /\.less$/,
        use: [
          {loader: 'style-loader' // creates style nodes from JS strings
      }, {
        loader: 'css-loader', // translates CSS into CommonJS
        options:{ importLoaders: 1}
      },
            {
                loader: 'less-loader',
                options: {
                    javascriptEnabled: true
                }
            }]
      },
      {
        test: /\.(sa|sc|c)ss$/,
        use: ['style-loader', 'css-loader', 'postcss-loader', {
            loader: 'sass-loader',
            options: { implementation: sass }
          }
        ]
      },
    ]
  }
`

package.json
```
[{
  "name": "tensor-base-template",
  "version": "0.1.0",
  "private": true,
  "homepage": ".",
  "devDependencies": {
    "@types/chai": "4.1.4",
    "@types/enzyme": "3.1.13",
    "@types/jest": "23.3.1",
    "@types/lodash": "4.14.116",
    "@types/mocha": "5.2.5",
    "@types/node": "10.9.2",
    "@types/react": "16.4.12",
    "@types/react-dom": "16.0.7",
    "@types/react-redux": "6.0.6",
    "@types/react-router-dom": "4.3.0",
    "@types/redux": "3.6.31",
    "@types/selenium-webdriver": "3.0.10",
    "@types/webpack-env": "1.13.6",
    "autoprefixer": "9.2.0",
    "browser-sync": "2.26.3",
    "browser-sync-webpack-plugin": "2.2.2",
    "cache-loader": "1.2.2",
    "chai": "4.1.2",
    "chai-as-promised": "7.1.1",
    "copy-webpack-plugin": "4.5.2",
    "core-js": "2.5.7",
    "cross-env": "5.2.0",
    "css-loader": "1.0.0",
    "enzyme": "3.5.0",
    "enzyme-adapter-react-16": "1.3.0",
    "enzyme-to-json": "3.3.4",
    "file-loader": "2.0.0",
    "fork-ts-checker-webpack-plugin": "0.4.9",
    "friendly-errors-webpack-plugin": "1.7.0",
    "generator-jhipster": "5.7.0",
    "html-webpack-plugin": "3.2.0",
    "husky": "1.1.0",
    "identity-obj-proxy": "3.0.0",
    "jest": "23.5.0",
    "jest-junit": "5.1.0",
    "jest-sonar-reporter": "2.0.0",
    "json-loader": "0.5.7",
    "less": "^3.9.0",
    "less-loader": "^4.1.0",
    "lint-staged": "7.3.0",
    "mini-css-extract-plugin": "0.4.2",
    "mocha": "5.2.0",
    "moment-locales-webpack-plugin": "1.0.7",
    "optimize-css-assets-webpack-plugin": "5.0.0",
    "postcss-loader": "3.0.0",
    "prettier": "1.14.3",
    "protractor": "5.4.0",
    "react-infinite-scroller": "1.2.0",
    "redux-mock-store": "1.5.3",
    "rimraf": "2.6.2",
    "sass": "1.13.0",
    "sass-loader": "7.1.0",
    "simple-progress-webpack-plugin": "1.1.2",
    "sinon": "6.1.5",
    "source-map-loader": "0.2.4",
    "sourcemap-istanbul-instrumenter-loader": "0.2.0",
    "stripcomment-loader": "0.1.0",
    "style-loader": "0.22.1",
    "swagger-ui": "2.2.10",
    "terser-webpack-plugin": "1.0.2",
    "thread-loader": "1.2.0",
    "to-string-loader": "1.1.5",
    "ts-jest": "23.1.4",
    "ts-loader": "4.5.0",
    "ts-node": "7.0.1",
    "tslint": "5.11.0",
    "tslint-config-prettier": "1.15.0",
    "tslint-eslint-rules": "5.4.0",
    "tslint-loader": "3.6.0",
    "tslint-react": "3.6.0",
    "typescript": "3.0.1",
    "webpack": "4.17.1",
    "webpack-cli": "3.1.0",
    "webpack-dev-server": "3.1.6",
    "webpack-merge": "4.1.4",
    "webpack-notifier": "1.7.0",
    "workbox-webpack-plugin": "3.4.1",
    "write-file-webpack-plugin": "4.3.2",
    "xml2js": "0.4.19"
  },
  "dependencies": {
    "@rowno/sparkline": "^3.0.1",
    "antd": "^3.11.2",
    "axios": "^0.18.0",
    "bootstrap": "^4.1.1",
    "classnames": "^2.2.5",
    "enquire-js": "^0.2.1",
    "immutability-helper": "^2.7.0",
    "immutable": "^3.8.2",
    "lodash": "^4.17.10",
    "moment": "^2.19.3",
    "moment-timezone": "^0.5.14",
    "peity-react": "^0.0.7",
    "prop-types": "^15.5.10",
    "rc-drawer": "^1.4.4",
    "react": "^16.4.12",
    "react-container-query": "^0.11.0",
    "react-custom-scrollbars": "^4.2.1",
    "react-dom": "^16.4.7",
    "react-helmet": "^5.2.0",
    "react-hot-loader": "3.1.1",
    "react-infinite-scroller": "^1.1.4",
    "react-loadable": "^5.4.0",
    "react-redux": "5.0.7",
    "react-redux-spinner": "^1.1.3",
    "react-router": "^4.2.0",
    "react-router-dom": "4.3.1",
    "react-router-redux": "^5.0.0-alpha.6",
    "redux": "^3.7.2",
    "redux-act": "^1.3.0",
    "redux-devtools": "3.4.1",
    "redux-devtools-dock-monitor": "1.1.3",
    "redux-devtools-extension": "^2.13.7",
    "redux-devtools-log-monitor": "1.4.0",
    "redux-logger": "^3.0.6",
    "redux-promise-middleware": "5.1.1",
    "redux-thunk": "^2.2.0"
  },
  "scripts": {
    "prettier:format": "prettier --write \"src/**/*.{json,ts,tsx,css,scss}\"",
    "lint": "tslint --project tsconfig.json -e 'node_modules/**'",
    "lint:fix": "npm run lint -- --fix",
    "cleanup": "rimraf target/www",
    "start": "npm run webpack:dev",
    "start-tls": "npm run webpack:dev -- --env.tls",
    "test": "npm run lint && jest --coverage --logHeapUsage -w=2 --config src/test/javascript/jest.conf.js",
    "test:watch": "npm test -- --watch",
    "webpack:dev": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --port=9060 --env.stats=minimal",
    "webpack:dev-verbose": "npm run webpack-dev-server -- --config webpack/webpack.dev.js --inline --port=9060 --profile --progress --env.stats=normal",
    "webpack:build:main": "npm run webpack -- --config webpack/webpack.dev.js --env.stats=minimal",
    "webpack:build": "npm run cleanup && npm run webpack:build:main",
    "webpack:prod:main": "npm run webpack -- --config webpack/webpack.prod.js --profile",
    "webpack:prod": "npm run cleanup && npm run webpack:prod:main",
    "webpack:test": "npm run test",
    "webpack-dev-server": "node --max_old_space_size=4096 node_modules/webpack-dev-server/bin/webpack-dev-server.js",
    "webpack": "node --max_old_space_size=4096 node_modules/webpack/bin/webpack.js"
  },
  "lint-staged": {
    "src/**/*.js": [
      "prettier --tab-width 2 --print-width 100 --single-quote --trailing-comma all --no-semi --parser babylon --write"
    ]
  }
}
]
```

**Comment by WangXiaoXiaoG** [comment]
If the plug-in version（less-loader） number is 6 or higher：   
 "less-loader": "^6.1.0",   
  "less": "^2.7.3",


The new way of writing it is
   {
              loader: "less-loader",
              options: {
                            lessOptions: {
                            javascriptEnabled: true,
                    }
                }
       }

**Comment by ruofee** [comment]
> If the plug-in version（less-loader） number is 6 or higher：
> "less-loader": "^6.1.0",
> "less": "^2.7.3",
> 
> The new way of writing it is
> {
> loader: "less-loader",
> options: {
> lessOptions: {
> javascriptEnabled: true,
> }
> }
> }

Format code style:
```javascript
{
  loader: 'less-loader',
  options: {
    lessOptions: {
      javascriptEnabled: true
    }
  }
}
```

**Comment by yanhaijing** [comment]
@afc163 less4已经不支持less中嵌入js了，现在只能降级成less3 才能避免这个报错
colorPalette 新的less对自定义函数的支持，需要改写成插件，不过更建议用postcss来实现类似功能
https://github.com/ant-design/ant-design/blob/master/components/style/color/colorPalette.less

参考：https://stackoverflow.com/questions/58343406/how-to-replace-the-deprecated-javascriptenabled-option-in-less-loader-with-a-new

**Comment by fullmoooooon** [comment]
main.js中引入ant-design-vue/dist/antd.less之后报错，解决方法
1. 安装 npm install less@3.13.0 less-loader@7.1.0 --save-dev （less要4以下，less-loader要8以下）
2. vue.config.js中加入css.loaderOptions.less.lessOptions.modifyVars配置[就是这个配置](https://www.antdv.com/docs/vue/customize-theme-cn/#%E5%9C%A8-vue-cli-3-%E4%B8%AD%E5%AE%9A%E5%88%B6%E4%B8%BB%E9%A2%98)，这个配置必须要加！！
3. 加完之后重启就ok了

**Comment by allenGKC** [comment]
> @afc163 less4已经不支持less中嵌入js了，现在只能降级成less3 才能避免这个报错
> colorPalette 新的less对自定义函数的支持，需要改写成插件，不过更建议用postcss来实现类似功能
> https://github.com/ant-design/ant-design/blob/master/components/style/color/colorPalette.less
> 
> 参考：https://stackoverflow.com/questions/58343406/how-to-replace-the-deprecated-javascriptenabled-option-in-less-loader-with-a-new

@yanhaijing 只能通过降低less版本嘛，有其他解决方案吗？

**Comment by allenGKC** [comment]
> If the plug-in version（less-loader） number is 6 or higher：
> "less-loader": "^6.1.0",
> "less": "^2.7.3",
> 
> The new way of writing it is
> {
> loader: "less-loader",
> options: {
> lessOptions: {
> javascriptEnabled: true,
> }
> }
> }

@ruofee 只能通过降低less版本嘛，有其他解决方案吗？

**Comment by yanhaijing** [comment]
@allenGKC 没有吧，除非antd自己升级less版本。。。

**Comment by allenGKC** [comment]
@yanhaijing 好吧，谢谢，降级去了：）

**Comment by afc163** [comment]
@yanhaijing @allenGKC 请开启 javascriptEnabled 。

**Comment by yanhaijing** [comment]
> @afc163 less4已经不支持less中嵌入js了，现在只能降级成less3 才能避免这个报错
> colorPalette 新的less对自定义函数的支持，需要改写成插件，不过更建议用postcss来实现类似功能
> https://github.com/ant-design/ant-design/blob/master/components/style/color/colorPalette.less
> 
> 参考：https://stackoverflow.com/questions/58343406/how-to-replace-the-deprecated-javascriptenabled-option-in-less-loader-with-a-new

@afc163 看看这个，开启 javascriptEnabled的前提是使用less 3.x，现在新建的项目 默认是less4.x了 ，所以需要手动降级下less版本才可以

**Comment by afc163** [comment]
less 4 也没问题的，我们用的也是 less 4.x 版本：https://github.com/ant-design/antd-tools/blob/36de3f7c9737e1898baffdf6bc145da434a0703f/package.json#L67

**Comment by allenGKC** [comment]
@afc163  @yanhaijing  亲测一下配置可以生效
```
"less": "^4.1.1",
"less-loader": "^10.0.1",
```

webpack:
```
{
        test: /(\.less)$/,
        use: [
          'style-loader',
          'css-loader',
          {
            loader: 'less-loader',
            options: {
              lessOptions: {
                javascriptEnabled: true,
              },
            },
          },
        ],
},
```

**Comment by 7chenys** [comment]
.bezierEasingMixin();
这个内联js应该怎么启用

**Comment by dupha** [comment]
Solution  https://blog.csdn.net/mingketao/article/details/124878657

**Comment by liu-xing-gang** [comment]
666👍👍👍

**Comment by liu-xing-gang** [comment]
> ![image](https://user-images.githubusercontent.com/11534583/31715423-6d07232a-b3c9-11e7-97d2-c1655cbb673e.png)
> 
> this less new version bug!!!!! close!

666👍👍👍
