### ISSUE TITLE
Missing exports field in package.json causes Yarn PnP resolution failures for subpath imports

### ISSUE THREAD

**Issue by OrlovAlexei** [ant-design/ant-design#56858]
### Reproduction link

[https://github.com/OrlovAlexei/antd-exports-issue](https://github.com/OrlovAlexei/antd-exports-issue)

### 1. Clone the repository

Clone the repository and follow the instructions in the README

```bash
git clone https://github.com/OrlovAlexei/antd-exports-issue.git
cd antd-exports-issue
```

### 2. Install dependencies

```bash
yarn install
```

### 3. Build the library and create a tarball

```bash
yarn build:lib
cd packages/lib && yarn pack && cd ../..
```

### 4. Install dependencies again (to pick up the tarball)

```bash
yarn install
```

### 5. Run the tests

```bash
cd packages/app && yarn vitest run
```

### What is expected?

Yarn PnP should be able to resolve subpath imports like antd/es/input/Search when antd has proper exports field configuration.

### What is actually happening?

Yarn PnP fails with "Qualified path resolution failed" error because antd doesn't declare these paths in exports.

| Environment | Info |
| --- | --- |
| antd | 6.2.3 |
| React | 18.2.0 |
| System | Lunux |
| Browser | N/A (Node.js/Yarn PnP) |

---
When consuming libraries that re-export antd components from subpaths (e.g., antd/es/input/Search), Yarn PnP fails to resolve these paths because it strictly validates package exports through the exports field. The error occurs when a library imports from antd subpaths and is consumed as a tarball/npm package (not workspace).

 Suggested Solution

Add exports field to package.json:

```json
{
  "exports": {
    ".": {
      "import": "./es/index.js",
      "require": "./lib/index.js",
      "types": "./es/index.d.ts"
    },
    "./es/_": "./es/_",
    "./lib/_": "./lib/_",
    "./locale/_": "./locale/_",
    "./dist/reset.css": "./dist/reset.css",
    "./package.json": "./package.json"
  }
}
```

## Additional Context

• Issue only reproduces when library is installed from npm/tarball, not with workspace:\*
• This affects real-world usage where design systems are published to npm
• Related to modern ESM/Node.js module resolution standards
• Similar issue: https://github.com/ant-design/ant-design/issues/46413

**Comment by MadCcc** [comment]
Sounds good, but need to care not break current import path.

**Comment by afc163** [comment]
## The `exports` field introduced in #57930 causes a TypeScript regression

The fix for Yarn PnP resolution breaks TypeScript type resolution for projects using `moduleResolution: "bundler"` (the default for Vite) or `"nodenext"`.

### Why

TypeScript's exports-based resolution does **NOT** perform directory/index lookups. It only tries direct file paths. Since antd's `es/` output mixes two structures — some modules are standalone files (`es/config-provider/context.d.ts`), others are directories with `index.d.ts` (`es/theme/interface/index.d.ts`) — no single wildcard pattern in `exports` can correctly resolve types for both:

| Pattern | File-based | Directory-based |
|---|---|---|
| `"./es/*": { "types": "./es/*.d.ts" }` | ✅ | ❌ |
| `"./es/*": { "types": "./es/*/index.d.ts" }` | ❌ | ✅ |
| `"./es/*": "./es/*"` | ❌ | ❌ |

This causes `FullToken` in `antd-style` (which deep-imports `AliasToken` from `antd/es/theme/interface`) to resolve as an empty interface, producing ~200+ `TS2339` errors.

### How to reproduce the TypeScript regression

```bash
mkdir test-antd-exports && cd test-antd-exports
npm init -y
npm install antd@6.4.0 antd-style typescript@5
cat > tsconfig.json << 'TSConfig'
{
  "compilerOptions": {
    "moduleResolution": "bundler",
    "strict": true
  }
}
TSConfig
cat > test.ts << 'TS'
import { createStyles } from 'antd-style';
const useStyles = createStyles(({ token }) => ({
  text: { color: token.colorText },
}));
TS
npx tsc --noEmit
# TS2339: Property 'colorText' does not exist on type 'FullToken'.
```

### How to reproduce the original Yarn PnP issue

If we want to re-introduce `exports` for Yarn PnP support, here's how to reproduce the original issue AND verify that the new `exports` doesn't break TypeScript:

1. **Yarn PnP reproduction** (original issue):
   ```bash
   git clone https://github.com/OrlovAlexei/antd-exports-issue
   cd antd-exports-issue
   yarn install
   yarn build:lib
   cd packages/lib && yarn pack && cd ../..
   yarn install
   yarn build:app
   # Without exports field: "Qualified path resolution failed"
   ```

2. **TypeScript verification** (must not regress):
   ```bash
   # After adding exports, verify in a bundler-mode project:
   mkdir ts-check && cd ts-check
   npm init -y
   npm install antd antd-style typescript
   # tsconfig with moduleResolution: "bundler"
   # Use antd-style's createStyles with token properties
   npx tsc --noEmit
   # MUST pass with 0 errors
   ```

Any future PR that re-adds `exports` must pass **both** scenarios.

### Possible paths forward

1. **Generate re-export stubs** — create `es/theme/interface.d.ts` that re-exports from `./theme/interface/index.js`, eliminating directory-only modules so `"./es/*.d.ts"` works universally (169 directories need stubs currently)
2. **Restructure build output** — make all modules file-based (no `index.d.ts` in subdirectories)
3. **Keep `exports` removed** — Yarn PnP users can add `packageExtensions` in `.yarnrc.yml` as a workaround

I've opened #57968 to remove `exports` for now.

**Comment by afc163** [comment]
Real-world CI failure caused by the `exports` field added in #57930: https://github.com/ant-design/ant-design-pro/actions/runs/25850042548/job/75954108350?pr=11783

**Comment by yoyo837** [comment]
Reopening this because #57930 was reverted in #57968.

**Comment by LeonxLJX** [comment]
I'd like to take this one — I'll follow up with a PR. (claiming via @LeonxLJX)

**Comment by LeonxLJX** [comment]
Hi! I'd like to fix the missing `exports` field for Yarn PnP. Plan: add the exports map, verify resolution, add a test. May I be assigned?
