### PR TITLE
fix: remove exports field to fix TypeScript module resolution

### LINKED ISSUE #56858: Missing exports field in package.json causes Yarn PnP resolution failures for subpath imports
### Reproduction link

[https://github.com/OrlovAlexei/antd-exports-issue](https://github.com/OrlovAlexei/antd-exports-issue)

### 1. Clone the repository

Clone the repository and follow the instructions in the README

```bash
git clone https://github.com/OrlovAlexei/antd-exports-issue.git
cd antd-exports-issue
```

### 2. Install dependencies

```bash
yarn install
```

### 3. Build the library and create a tarball

```bash
yarn build:lib
cd packages/lib && yarn pack && cd ../..
```

### 4. Install dependencies again (to pick up the tarball)

```bash
yarn install
```

### 5. Run the tests

```bash
cd packages/app && yarn vitest run
```

### What is expected?

Yarn PnP should be able to resolve subpath imports like antd/es/input/Search when antd has proper exports field configuration.

### What is actually happening?

Yarn PnP fails with "Qualified path resolution failed" error because antd doesn't declare these paths in exports.

| Environment | Info |
| --- | --- |
| antd | 6.2.3 |
| React | 18.2.0 |
| System | Lunux |
| Browser | N/A (Node.js/Yarn PnP) |

---
When consuming libraries that re-export antd components from subpaths (e.g., antd/es/input/Search), Yarn PnP fails to resolve these paths because it strictly validates package exports through the exports field. The error occurs when a library imports from antd subpaths and is consumed as a tarball/npm package (not workspace).

 Suggested Solution

Add exports field to package.json:

```json
{
  "exports": {
    ".": {
      "import": "./es/index.js",
      "require": "./lib/index.js",
      "types": "./es/index.d.ts"
    },
    "./es/_": "./es/_",
    "./lib/_": "./lib/_",
    "./locale/_": "./locale/_",
    "./dist/reset.css": "./dist/reset.css",
    "./package.json": "./package.json"
  }
}
```

## Additional Context

• Issue only reproduces when library is installed from npm/tarball, not with workspace:\*
• This affects real-world usage where design systems are published to npm
• Related to modern ESM/Node.js module resolution standards
• Similar issue: https://github.com/ant-design/ant-design/issues/46413

### PR DESCRIPTION
**Pull request by afc163**
### 🤔 What is the nature of this change?

- [x] 🐞 Bug fix

### 🔗 Related Issue

close #56858

### 💡 Background and Solution

**Problem**

PR #57930 (commit 597f94c1) added an `exports` field to `package.json` to support Yarn PnP subpath resolution. However, this breaks TypeScript type resolution under `moduleResolution: "bundler"` (Vite default) and `"nodenext"`, causing ~200+ `TS2339` errors in downstream projects.

**CI failure**: https://github.com/ant-design/ant-design-pro/actions/runs/25850042548/job/75954108350?pr=11783

**Root cause**

TypeScript's exports-based resolution does **NOT** perform directory/index lookups. When resolving `antd/es/theme/interface`, it only tries `./es/theme/interface.d.ts` — it will never check `./es/theme/interface/index.d.ts`.

Since antd's `es/` output uses a mixed structure:

- File-based: `es/config-provider/context.d.ts`
- Directory-based: `es/theme/interface/index.d.ts`

No single wildcard pattern in `exports` can correctly resolve types for both cases:

| Pattern | File-based | Directory-based |
|---|---|---|
| `"./es/*": { "types": "./es/*.d.ts" }` | ✅ | ❌ |
| `"./es/*": { "types": "./es/*/index.d.ts" }` | ❌ | ✅ |
| `"./es/*": "./es/*"` | ❌ | ❌ |

`antd-style` deep-imports `AliasToken` from `antd/es/theme/interface`. When that import fails to resolve, `FullToken` becomes an empty interface, causing all token properties to report TS2339.

**Solution**

Remove the `exports` field to restore traditional Node.js module resolution (which supports directory/index lookups). The `main`, `module`, and `typings` fields continue to work correctly for the main entry point.

Yarn PnP users can add `packageExtensions` in `.yarnrc.yml` as a workaround:

```yaml
packageExtensions:
  "antd@*":
    exports:
      "./es/*": "./es/*"
      "./lib/*": "./lib/*"
```

**Test**

Added `tests/dekko/exports.test.ts`, which verifies deep subpath type imports resolve correctly under `moduleResolution: "bundler"` in a temporary project:
- ✅ Passes when `exports` field is absent
- ❌ Fails when the broken `exports` from #57930 is present, reporting `TS2307: Cannot find module 'antd/es/theme/interface'`

### 📝 Changelog

| Language | Description |
| -------- | ----------- |
| 🇺🇸 English | Remove `exports` field from package.json that broke TypeScript type resolution under `moduleResolution: "bundler"`. |
| 🇨🇳 Chinese | 移除 `package.json` 中导致 `moduleResolution: "bundler"` 下 TypeScript 类型解析失败的 `exports` 字段。 |

### CODE REVIEW

**Review by meet-student — DISMISSED** [review]

**Comment by yoyo837** [comment]
需要加bug version

**Review by li-jia-nan — DISMISSED** [review]

**Review by li-jia-nan — DISMISSED** [review]

**Review by li-jia-nan — APPROVED** [review]
