### ISSUE TITLE
来自 es/theme/util/genStyleUtils.d.ts 的 TS 报错

### ISSUE THREAD

**Issue by ylqylq001** [ant-design/ant-design#50970]
### Steps to reproduce

1. 下载 antd 的 npm 依赖至最新版。
2. 等待 WebStrom 解析并构建索引。
3. 访问 WebStrom 项目错误提示。

![屏幕截图 2024-09-23 165659](https://github.com/user-attachments/assets/8575eeee-6fa0-4243-8d47-ae645c2654b7)

### What is expected?

WebStrom 不存在报错提示。

### What is actually happening?

错误源头：genStyleUtils.d.ts 文件，位于 antd 项目下的 es/theme/util/genStyleUtils.d.ts 路径。
一共七个 Typescript 类型错误：
1. TS2304: Cannot find name 'CompTokenMap'.
2. TS2304: Cannot find name 'C_1'.
3. TS2304: Cannot find name 'C_1_1'.
5. TS2552: Cannot find name 'C_1_1'. Did you mean 'C_1'?
6. TS2552: Cannot find name 'C_2_1'. Did you mean 'C_2'?

![微信截图_20240923164308](https://github.com/user-attachments/assets/3f44edab-0eb4-4657-a356-52822e34f6be)

| Environment | Info |
| --- | --- |
| antd | 5.21.0 |
| React | 18.3 |
| System | Windows 11 |
| Browser | EDGE 128.0.2739.54 |

**Comment by ylqylq001** [comment]
> 看起来像是依赖问题，重装一下确认 cssinjs-util 这个库是不是最新的试试

我把整个 node_modules 全删掉再重新 `npm install` 一遍，依旧会出现这个提示

**Comment by bwlt** [comment]
Hi, the reproduction link of the bot (https://u.ant.design/repro) does not work.  
I have found how to create a reproduction link here https://new-issue.ant.design/ but with the codepen platform it's limited because it does not allow to perform typescript compilation.

I have created a reproduction here: https://codesandbox.io/p/devbox/jdvv8y

details of the reproduction:
- using the last antd version 5.21.2
- running the `build` task from the terminal
- tsconfig.json `compilerOptions.skipLibCheck` is not set (defaults to true, this is why the compiler checks the antd code)
- it also fails on rc-picker, but this other issue is out of this context

As a workaround I'm using an older version of antd, because I don't want to set the skipLibCheck options to true.

thank you!

**Comment by tommy26tan** [comment]
bro @bwlt  which older version can ?

**Comment by bwlt** [comment]
Hi @tommy26tan, working with version antd@5.18.3. I have updated the previous comment as a reference.

**Comment by tommy26tan** [comment]
@bwlt  Thanks bro, though it give me less error to fall back but still have 

node_modules/rc-menu/lib/index.d.ts:5:29 - error TS7016: Could not find a declaration file for module './context/PathContext'. 'C:/Users/a5136352/Downloads/VS_code_/e2-studio-vscode-renesas-fsp-ui-smart-configurator/node_modules/rc-menu/lib/context/PathContext.js' implicitly has an 'any' type.

Alternative solution other than skipLibCheck=true, I import them as commonJS module.

const Cascader = require('antd').Cascader;
const ConfigProvider = require('antd').ConfigProvider;
const RightOutlined = require('@ant-design/icons').RightOutlined;
