### ISSUE TITLE
typescript error - regression in v4

### ISSUE THREAD

**Issue by pdeva** [ant-design/ant-design#22708]
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
compile with typescript 3.7.5 without allowSyntheticDefaultImports flag set

### What is expected?
compiles without issues

### What is actually happening?
Tons of compile errors like this:

```

node_modules/@ant-design/icons/lib/components/Icon.d.ts:1:8 - error TS1259: Module '"D:/adcode/dashboard/node_modules/@types/react/index"' can only be default-i
mported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:62:1
    62 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | windows 10 |
| Browser | firefox 74 |

---
`allowSyntheticDefaultImports` flag is specifically *not* required by antd.

even mentioned here: 
https://github.com/ant-design/ant-design/issues/19276#issuecomment-544108302

the changes in antd 4, make it a requirement.

if its a requirement now, document it, otherwise please fix it.

**Comment by pdeva** [comment]
this issue still remains as of antd 4.1.4

**Comment by pdeva** [comment]
seems while it was fixed in icons package, rest of packages still have this issue in 4.1.4

```

node_modules/antd/lib/_util/getRenderPropValue.d.ts:1:8 - error TS1259: Module '"/home/pdeva/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:64:1
    64 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

node_modules/rc-menu/es/MenuItemGroup.d.ts:1:8 - error TS1259: Module '"/home/pdeva/code/dashboard/node_modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~
```

**Comment by yoyo837** [comment]
Is it possible to upgrade to ts 3.8+ and update @types/react ？

**Comment by chunliu** [comment]
I hit the same issue with 4.2.0, and have to temporarily turn allowSyntheticDefaultImports on. Need a fix.

**Comment by pdeva** [comment]
still present in 4.2.3

**Comment by afc163** [comment]
Fixed in #23381

**Comment by chunliu** [comment]
@afc163 The problem doesn't seem to be fixed by #23381 completely. At least the components, rc-menu, rc-tooltip, rc-tree-select, and rc-trigger, are still using `import React from 'react';`. There could be other components as well.

**Comment by pdeva** [comment]
still seeing this error in `4.4.3`

```


node_modules/antd/node_modules/rc-menu/lib/MenuItemGroup.d.ts:1:8 - error TS1259: Module '"C:/code/dashboard/node_
modules/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:65:1
    65 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allo
wSyntheticDefaultImports' flag.

node_modules/antd/node_modules/rc-menu/lib/SubMenu.d.ts:1:8 - error TS1259: Module '"C:/code/dashboard/node_module
s/@types/react/index"' can only be default-imported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';

```
