### ISSUE TITLE
Typescript error for some components in v3.10.0

### ISSUE THREAD

**Issue by kevinkam** [ant-design/ant-design#12499]
- [x] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Version
3.10.0

### Environment
5.0 (Macintosh; Intel Mac OS X 10_14_0) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/69.0.3497.100 Safari/537.36

### Reproduction link
[https://github.com/ant-design/ant-design/blob/master/components/breadcrumb/Breadcrumb.tsx](https://github.com/ant-design/ant-design/blob/master/components/breadcrumb/Breadcrumb.tsx)

### Steps to reproduce
when I run my project, if import any antdesign component will show error, otherwise is fine
error message is 
```
/node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts
ERROR in /node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts(25,52):
TS2694: Namespace '"/node_modules/@types/prop-types/index"' has no exported member 'ReactNodeLike'.
```

### What is expected?
it should use PropTypes.ReactNode, not PropTypes.ReactNodeLike

### What is actually happening?
type error

**Comment by kevinkam** [comment]
It's working in 3.9.3

**Comment by ycjcl868** [comment]
It's working in [my project](https://codesandbox.io/s/ymw5rmjwo1) (antd: `3.10.0`, typescript: `3.1.1`).
Could you please give me a reproduction link using [`Codesandbox`](https://codesandbox.io/) or [`CodePen`](https://codepen.io)

**Comment by kevinkam** [comment]
@ycjcl868 I found that is typescript version issue, I was using typescript `3.0.3` to run antd `3.10.0`, after I upgrade my typescript to `3.1.1`, everything is fine now.

**Comment by kevinkam** [comment]
please help close it if not consider as a bug.
(I don't know need to support typescript < `3.1.1` or not)

**Comment by magnnus** [comment]
I have met  a similar error in my project. 
`node_modules/antd/lib/transfer/index.d.ts
(78,58): error TS2694: Namespace '"/Users/.../node_modules/@types/prop-types/index"' has no exported member 'ReactNodeLike'.`

**Comment by bagr001** [comment]
I have the same problem with Breadcrumb typings. TS 3.1.1 does not work for me :-/

**Comment by SolidZORO** [comment]
These similar errors exist in my project too.

----

TS 3.1.1
antd 3.10.0

----

> 
17:38:25 ➜ CAPTAIN wolf (git:master) tsc
node_modules/antd/lib/breadcrumb/Breadcrumb.d.ts:25:52 - error TS2694: Namespace '"/____PATH____/____PROJECT____/node_modules/@types/prop-types/index"' has no exported member 'ReactNodeLike'.

25         separator: PropTypes.Requireable<PropTypes.ReactNodeLike>;
                                                      ~~~~~~~~~~~~~


....


30         label: PropTypes.Requireable<string | number | boolean | {} | PropTypes.ReactElementLike | PropTypes.ReactNodeArray>;
                                                                                   ~~~~~~~~~~~~~~~~

node_modules/antd/lib/form/FormItem.d.ts:30:110 - error TS2694: Namespace '"/____PATH____/____PROJECT____/node_modules/@types/prop-types/index"' has no exported member 'ReactNodeArray'.

30         label: PropTypes.Requireable<string | number | boolean | {} | PropTypes.ReactElementLike | PropTypes.ReactNodeArray>;

....

**Comment by wonderfulMan** [comment]
![image](https://user-images.githubusercontent.com/29673031/46492579-8a62e800-c840-11e8-81c4-b6095a0ae631.png)

    "typescript": "^3.1.1"
    "antd": "^3.10.0"

why is not work ? I need help

**Comment by wonderfulMan** [comment]
why is not work ? I need help

![image](https://user-images.githubusercontent.com/29673031/46492720-f5142380-c840-11e8-8811-76e7bb764b96.png)
typescript: 3.1.1
antd: 3.1.0

**Comment by kevinkam** [comment]
Hi guys, I found another solution, it's not typescript version issue, try to add `"skipLibCheck": true` inside your `tsconfig.json` file, it will be solved.

**Comment by kevinkam** [comment]
![screen shot 2018-10-05 at 10 35 53 am](https://user-images.githubusercontent.com/2314515/46513305-7fcd4080-c88a-11e8-84a9-44f955cdd2aa.png)

**Comment by kevinkam** [comment]
![screen shot 2018-10-05 at 10 37 26 am](https://user-images.githubusercontent.com/2314515/46513342-af7c4880-c88a-11e8-9160-982bd10a7057.png)

**Comment by wonderfulMan** [comment]
> Hi guys, I found another solution, it's not typescript version issue, try to add `"skipLibCheck": true` inside your `tsconfig.json` file in `compilerOptions` field, I think it will be solved.

Thanks for your help.

**Comment by wonderfulMan** [comment]
> I am not sure if `"skipLibCheck": true` is a good approach to solving this. It seems like temporary fix but not a root cause solution. Imho it needs further investigation...
> 
> What is your environment configuration? My:
> 
> * Node v10.11.0
> * NPM 6.1.0
> * Yarn 1.10.1
> * TS 3.1.1

my:
> * Node v10.11.0
> * NPM 6.1.0
> * Yarn 1.10.1
> * TS 3.1.1
> * Antd 3.1.0
> * Webpack 4.20.0

**Comment by kevinkam** [comment]
@bagr001 Ya, I agree with you, the actual problem is `ReactNodeLike`, I have check between `3.9.3` and `3.10.0`, in `3.9.3` it still using `ReactNode`, but in `3.10.0` the typing changed to `ReactNodeLike`
my:
- Node 10.11.0
- NPM 6.4.1
- YARN 0.15.1
- TS 3.1.1

**Comment by kevinkam** [comment]
@ycjcl868 FYI, as you can see the `PropTypes` does not have any property call `ReactNodeLike`

![screen shot 2018-10-05 at 2 34 16 pm](https://user-images.githubusercontent.com/2314515/46519672-c717f900-c8ab-11e8-9e25-34a230e4a573.png)

**Comment by ycjcl868** [comment]
It's a bug. will fix later.

**Comment by kevinkam** [comment]
@ycjcl868 15.6.2

**Comment by ycjcl868** [comment]
the reason may be [@types/prop-types](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/types/prop-types/index.d.ts#L58) updated 8 days ago. 
so upgrade the `@types/prop-types` may solve the problem.

**Comment by ycjcl868** [comment]
@KevinBon upgrade `@types/prop-types` to `15.5.6`, reinstall and see whether the problem solved.

**Comment by bagr001** [comment]
@ycjcl868 This works! Thank you for your help :)

**Comment by kevinkam** [comment]
@ycjcl868 I didn't use `@types/prop-types` in my project, so right now I need to manually install this dependency, is it better if antd update `@types/prop-types` from `15.5.4` to `15.5.6` in antd `package.json`?
[https://github.com/ant-design/ant-design/blob/master/package.json](https://github.com/ant-design/ant-design/blob/master/package.json)

**Comment by ycjcl868** [comment]
@kevinkam  `"@types/prop-types": "^15.5.4"` in antd package.json will install `@types/prop-types 15.5.6` automatically

**Comment by raptoria** [comment]
is this going to be fixed in the next version of antd?

**Comment by ifyour** [comment]
> Hi guys, I found another solution, it's not typescript version issue, try to add `"skipLibCheck": true` inside your `tsconfig.json` file in `compilerOptions` field, I think it will be solved.

Nice, Thanks a lot!
