### PR TITLE
fix: proper react import

### LINKED ISSUE #22708: typescript error - regression in v4
- [x ] I have searched the [issues](https://github.com/ant-design/ant-design/issues) of this repository and believe that this is not a duplicate.

### Reproduction link
[https://github.com/ant-design/ant-design](https://github.com/ant-design/ant-design)

### Steps to reproduce
compile with typescript 3.7.5 without allowSyntheticDefaultImports flag set

### What is expected?
compiles without issues

### What is actually happening?
Tons of compile errors like this:

```

node_modules/@ant-design/icons/lib/components/Icon.d.ts:1:8 - error TS1259: Module '"D:/adcode/dashboard/node_modules/@types/react/index"' can only be default-i
mported using the 'allowSyntheticDefaultImports' flag

1 import React from 'react';
         ~~~~~

  node_modules/@types/react/index.d.ts:62:1
    62 export = React;
       ~~~~~~~~~~~~~~~
    This module is declared with using 'export =', and can only be used with a default import when using the 'allowSyntheticDefaultImports' flag.

```

| Environment | Info |
|---|---|
| antd | 4.0.4 |
| React | 16.12 |
| System | windows 10 |
| Browser | firefox 74 |

---
`allowSyntheticDefaultImports` flag is specifically *not* required by antd.

even mentioned here: 
https://github.com/ant-design/ant-design/issues/19276#issuecomment-544108302

the changes in antd 4, make it a requirement.

if its a requirement now, document it, otherwise please fix it.

### PR DESCRIPTION
**Pull request by pdeva**
fix for #22708

### 🤔 This is a ...

- [ ] New feature
- [x] Bug fix
- [ ] Site / document update
- [ ] Component style update
- [ ] TypeScript definition update
- [ ] Refactoring
- [ ] Code style optimization
- [ ] Test Case
- [ ] Branch merge
- [ ] Other (about what?)

### 🔗 Related issue link

close #22708

### 📝 Changelog

| Language   | Changelog |
| ---------- | --------- |
| 🇺🇸 English |  Fix TS compile error without `allowSyntheticDefaultImports`. |
| 🇨🇳 Chinese | 修复未设置 `allowSyntheticDefaultImports` TS 报错的问题。 |

### ☑️ Self Check before Merge

⚠️ Please check all items below before review. ⚠️ 

- [x] Doc is updated/provided or not needed
- [x] Demo is updated/provided or not needed
- [x] TypeScript definition is updated/provided or not needed
- [x] Changelog is provided or not needed

### CODE REVIEW

**Comment by yoyo837** [comment]
https://github.com/ant-design/ant-design/blob/54d050324a10688542ab3ed56f5e3b8558e5b066/components/tree/utils/iconUtil.tsx#L1

https://github.com/ant-design/ant-design/blob/54d050324a10688542ab3ed56f5e3b8558e5b066/components/select/utils/iconUtil.tsx#L1

**Comment by afc163** [comment]
ping @pdeva

**Comment by pdeva** [comment]
done

**Review by yoyo837 — APPROVED** [review]

**Comment by chunliu** [comment]
Does the release 4.4.0 include this fix?

**Comment by yoyo837** [comment]
Assuredly
